---
- hosts: mysql1
  vars:
    project_name: DCVS-ES
    project_url: git@10.45.156.100:DCVS/DCVS-ES.git
    flag_dirctory: /success
    base_dir: /root/codelibrary/es
  remote_user: root
  tasks:
    - name: remove directory if exists
      file:
        path: "{{ base_dir }}/{{  project_name }}"
        state: absent
      notify:
        - prepare flag directory
        - remove exists files
    - name: download git project codes
      command: git clone -b master "{{ project_url }}"  "{{ base_dir }}/{{ project_name }}"
    - name: prepare package script
      copy:
        src: "{{ base_dir }}/{{ project_name }}/tools/{{ item }}"
        dest: "{{ base_dir }}/{{ item }}"
        force: yes
        backup: yes
      loop:
        - package.sh
        - predefine.sh
        - set_param.sh
        - msort.sh
        - deploy.sh
        - recreate.sh
        - root_execute.sh
    - name: grant execute privilege
      command: chmod u+x "{{ base_dir }}/{{ item }}"
      loop:
        - package.sh
        - predefine.sh
        - set_param.sh
        - msort.sh
        - deploy.sh
        - recreate.sh
        - root_execute.sh
    - name: make a release package
      shell: "{{ base_dir }}/package.sh"
      notify:
        - prepare flag directory
        - confirm success
  handlers:
    - name: confirm success
      file:
        path: /success/s
        state: touch
    - name: make flag
      file:
        path: /success/r
        state: touch
      listen: remove exists files
    - name: prepare flag directory
      file:
        path: /success
        state: directory
